const { test, expect } = require('@playwright/test');

const { faker } = require('@faker-js/faker');

import { LoginPage } from '../pages/login.js';
import { Menus } from '../pages/menu.js';


test('Login Functionality', async ({ page }) => {
      const login = new LoginPage(page);
      await login.goto();
      await login.login('justin.barrett','AsWmQhbGqjgU');

      const menus = new Menus(page);
      await menus.Reportloginmenu( 'Reports', 'Reports', 2 , 'Incoming Cash Transfer');
 

//variables
      const date = new Date();
      const currentMonth = new Date().toLocaleString('en-US', { month: 'long' });
      const currectyear = date.getFullYear();  
      const now = new Date();
      const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
      const today = new Date().getDate();

//from date
      await page.locator('button').filter({ hasText: 'Pick a date' }).first().click();

      await page.getByRole('combobox').filter({ hasText: currectyear }).first().click();
      const yearOption = page.getByRole('option', { name: currectyear });
      await expect(yearOption).toBeVisible();
      await yearOption.click();
      await page.locator('button').filter({ hasText: currentMonth }).click();
      const MonthOption = page.getByRole('option', { name: currentMonth });
      await expect(MonthOption).toBeVisible();
      await MonthOption.click();
      await  page.getByRole('gridcell', { name: 1 }).first().click({ force: true });


//todate
      page.locator('button').filter({ hasText: 'Pick a date' }).last().click();
      await page.getByRole('combobox').filter({ hasText: currectyear }).first().click();
      const yearOption1 = page.getByRole('option', { name: currectyear });
      await expect(yearOption1).toBeVisible();
      await yearOption1.click();
      await page.locator('button').filter({ hasText: currentMonth }).click();
      const MonthOption1 = page.getByRole('option', { name: currentMonth });
      await expect(MonthOption1).toBeVisible();
      await MonthOption1.click();
      await  page.getByRole('gridcell', { name: today }).first().click({ force: true });

      await page.getByLabel('Email:').fill('Priyanka@onifytech.com');
      await page.getByRole('textbox', { name: 'Name: (Optional)' }).fill('Incomin Cash Report Generated by Automation testing')
      await page.getByRole('button', { name: 'Request' }).click();
      const message = page.getByText(
      'The Incoming Cash Report is being generated and will be sent to your email within a few minutes.',
      { exact: true }
);

await expect(message).toBeVisible();




  



})