const { test, expect } = require('@playwright/test');

const { faker } = require('@faker-js/faker');

import { LoginPage } from '../pages/login.js';
import { Menus } from '../pages/menu.js';


test('Login Functionality', async ({ page }) => {
      const login = new LoginPage(page);
      await login.goto();
      await login.login('justin.barrett','AsWmQhbGqjgU');

      const menus = new Menus(page);
      await menus.Reportloginmenu( 'Reports', 'Reports', 2 , 'Pending Documents');
 

      await page.getByRole('textbox', { name: 'Name: (Optional)' }).fill('Pending doc Report Generated by Automation testing')
      await page.getByRole('button', { name: 'Export' }).click();
      const message = page.getByText(
      'Success! The report has been exported.',
      { exact: true }
);

await expect(message).toBeVisible();




  



})