const { test, expect } = require('@playwright/test');

const { faker } = require('@faker-js/faker');

import { LoginPage } from '../pages/login.js';
import { Menus } from '../pages/menu.js';


test('Login Functionality', async ({ page }) => {
      const login = new LoginPage(page);
      await login.goto();
      await login.login('justin.barrett','AsWmQhbGqjgU');

      const menus = new Menus(page);
      await menus.Reportloginmenu( 'Reports', 'Reports', 2 , 'Term Accounts');
 

      await page.getByLabel('Email:').fill('Priyanka@onifytech.com');
      await page.getByRole('textbox', { name: 'Name: (Optional)' }).fill('Term Account Report Generated by Automation testing')
      await page.getByRole('button', { name: 'Request' }).click();
      const message = page.getByText(
      'The Term Accounts Report is being generated and will be sent to your email within a few minutes.',
      { exact: true }
);

await expect(message).toBeVisible();


  



})